### ISSUE TITLE
Update Kitsune

### ISSUE THREAD

**Issue by Mklj0** [LordEggNutz/Imrallon#25] opened 2017-10-29 04:50 UTC
Update of the Kitsune. Maybe just a general focus on the races history and creation during the war.

- [ ]  Race Name
- [ ]  Alignments Allowed
- [ ]  Using Book Rules?
- [ ]  Any special rules?
- [ ]  History
- [ ]  Locations/Regions
- [ ]  General Disposition
- [ ]  Deity Worshipped
- [ ]  Groups / Factions Associated With

**Comment by LordEggNutz** [comment] 2017-10-29 06:20
Created by Hermes or just favored by him?

**Comment by Mklj0** [comment] 2017-10-30 18:08
Depends on how we are doing all the races, I suppose. Dwarves were created aye? Or are we making exceptions for some? @LordEggNutz

**Comment by LordEggNutz** [comment] 2017-10-30 18:59
I think we should mix it up a bit.  Hephestus "creating" the dwarves made sense.

**Comment by LordEggNutz** [comment] 2017-10-30 19:05
Was there an idea that you wanted to run with @Mklj0?

**Comment by Mklj0** [comment] 2017-10-31 04:57
## Ideas

1. Hermes himself was a Kitsune

2. Kitsune had been created with their Shapeshifting capability by a meeting of intimacy between  Hermes and Aphrodite while in the form of foxes

3. Kitsune maintained the ability to Shapeshift into foxes and were gifted with speed to allow them to be stealthy messengers. These powers may have been lost afterwards, at least the speed was.

More to be added if thought of.

**Comment by LordEggNutz** [comment] 2017-11-01 17:37
I am digging #2 and #3 in that list.

**Comment by LordEggNutz** [comment] 2017-11-06 22:39
@Mklj0, Take a look at Issue #32

**Comment by Mklj0** [comment] 2017-11-07 18:08
@LordEggNutz Thanks for that. It will most likely help. Just need to find time to work on the overall lore for it.

**Comment by LordEggNutz** [comment] 2017-11-07 18:53
@Mklj0, no worries.  Just thinking of ways to keep things uniform so that we dont miss anything

**Comment by LordEggNutz** [comment] 2019-08-20 03:30
5ed homebrewed character block  [Source:](https://www.dandwiki.com/wiki/Kitsune_(5e_Race))

Kitsune Traits
> A race of anthropomorphic fox people who have magic in their blood and light shape-changing capabilities.
Ability Score Increase. Your Charisma score increases by 2.
Age. Kitsune reach adulthood at 16, cease physical aging in their early 20s and live to be a century and a half.
Alignment. Due to their nature of being a bit mischievous, kitsune are often chaotic. Even the most skilled monks find it difficult to ignore the desire to be a bit mischievous at times, but they tend to approach the trick in a much more planned out and guided manner. Kitsune are known to be both good and evil.
Size. Kitsune are generally on the smaller side of most humanoids ranging from 4'7 to the tallest being just under 6'. Weight wise kitsune are as light and agile as they look. Your size is Medium.
Speed. Your base walking speed is 30 feet. While not carrying anything in your hands you can drop to all fours and increase your movement speed to 35 feet.
Kitsune Awareness. You have the ability to hear falsehoods for what they are. You know if you hear a creature willingly lie. A creature hidden from divination magic reveals nothing.
Kitsune Trickery. You can appear as a human equivalent of yourself indefinitely using a very simple illusion magic, you cannot change alter your illusionary human self. A creature looking directly at you can make a Intelligence (Investigation) check, to tell that you are not what you appear to be, though they still cannot perceive your true form. The DC for this check is equal to 10 + your proficiency bonus + your Charisma modifier. This magic is detectable by spells such as detect magic and dispelled in an antimagic field or by a successful dispel magic. Your proficiency bonus is considered the level of the spell for the sake of dispel magic. If your illusion is dispelled you cannot use the effect again until after a long rest.
Languages. You can speak, read, and write Common.
Subrace. Pick one from Zenko or Yako.
Zenko
They are known as celestial kitsune since most are benevolent and kind. These kitsune tend to have the lighter fur colors, white, golden brown, grey, etc.

> Ability Score Increase. Your Wisdom score increases by 1.
Kitsune Divinity. You know the produce flame cantrip, with the exception that your flame is blue. When you reach 3rd level, you can cast the bless spell once and need to finish a long rest before you can cast it again. When you reach 5th level, you can also cast the calm emotions spell once and need to finish a long rest before you can cast it again. Charisma is your spellcasting ability for these spells.
Second Langauge. You can speak, read and write Celestial.
Yako
They are known as trickster kitsune since they are the ones more prone to their prankster heritage. These kitsune tend to have the darker fur colors, black, reddish brown, dark grey, etc.

> Ability Score Increase. Your Dexterity score increases by 1.
Kitsune Arcana. You know the produce flame cantrip, with the exception that your flame is blue. When you reach 3rd level, you can cast the cause fear[1] spell once and need to finish a long rest before you can cast it again. When you reach 5th level, you can also cast the phantasmal force spell once and need to finish a long rest before you can cast it again. Charisma is your spellcasting ability for these spells.
Second Langauge. You can speak, read and write Sylvan.

**Comment by LordEggNutz** [comment] 2019-08-20 03:44
Working on doing a reskin of a Tabaxi with options for half-breeds

**Comment by LordEggNutz** [comment] 2019-08-21 23:32
# Kitsune
Being born of both Aphrodite and Hermes, the kitsune embrace both the love and beauty from their mother and the mischief of their father.  When you walk through town, you will like see them as a beautiful woman or that of a vexatious child.  In the wilderness, you will likely encounter a playful fox.  Both would approach you with good intentions, but do delight in all sorts of harmless trickery and mischief.  They are prone to getting caught up in the stories of adventurers and may even join them, whether or not they know it, to satisfy their inquisitive nature.  Many kingdoms and powerful individuals employ kitsune as valued messengers, spies and thieves.

### Natural Shapeshifters
Aphrodite and Hermes had a child that was conceived while they were both in fox form. This child was named Kitsune, which transferred to the name of the race.  Kitsune can be born in either a humanoid form or a fox form.  This is dependent on what form the child's parents were in when it was conceived.  If they were both in humanoid form, the child will be born a humanoid and vice versa.  Kitsune will only mate when both are in the same form.  When they come of age generally between 50 and 75 years old, they will be gifted with their other natural form.  This comes spontaneously and generally during the night time hours.  If they are gifted with the humanoid race, it will be the same as their mother.  If they are gifted with a fox form, they tend to be brown tones to red in color.  Kitsune that are in arctic regions, they tend to be pure white.

### Endearing Pranksters
Kitsune are extremely inquisitive and fascinated with the people of the world and their stories.  This tends to have them find a natural fit with storytellers and loremasters.  Some find that they are suited for the theft of this knowledge and make excellent thieves and spies.  Regardless, Kitsune absolutely love to play pranks on others.  These are rarely anything more than simple, harmless tricks.  Anymore more may cause those around them to be less tolerant of them and cause them to be driven away.

### Kitsune Names
_TBD_
Male Names: _TBD_
Female Names: _TBD_

### Kitsune Traits
**Ability Score Increase**. Your Charisma score increases by 2, and your Dexterity score increases by 1.
**Age**. Kitsune mature slowly, achieving adulthood at around 50 to 75 years and can live up to around 700 years.
**Alignment**. The mischievous nature and general good nature of Kitsune tend to have them lean towards Chaotic Good alignments, however, it is not unknown to find them following the strict rule of Law or finding delight in the deeds of Evil.

**Closed** 2019-08-22 04:38 UTC
Labels: Races
